apiVersion: v1
kind: Service
metadata:
  name: nodejs-app-service
spec:
  selector:
    app.kubernetes.io/name: nodejs-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
  type: LoadBalancer
